name: result_dart
description: Result for dart. It is an implementation based on Kotlin Result and Swift Result.
version: 1.0.0
repository: https://github.com/Flutterando/result_dart

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  meta: ^1.3.0

dev_dependencies:
  test: any
  flutterando_analysis: ^0.0.1+2
